name       : kgpg
version    : 21.08.1
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kgpg-21.08.1.tar.xz : ba6b98f13716f2033f4eff4958881222e149ae9f4559c2a77524e300a13a9360
homepage   : https://kde.org/applications/utilities/org.kde.kgpg
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - akonadi-contacts-devel
    - gpgme-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
