name       : kgpg
version    : 21.12.1
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kgpg-21.12.1.tar.xz : 1178d8637f1bfa9228b99164d2c515bae3e9cb04d2806d583fa33b52dd0dad63
homepage   : https://kde.org/applications/utilities/org.kde.kgpg
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - akonadi-contacts-devel
    - gpgme-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
