name       : kgpg
version    : 18.12.1
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kgpg-18.12.1.tar.xz : 5e248416962161016c9aa8c8137a63a91e146bf014c08058bf3b313e241c59e5
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - pkgconfig(Qt5Gui)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcodecs-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
