name       : kgpg
version    : 21.08.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kgpg-21.08.3.tar.xz : 5a1d83393fc42aad5687463d8042d58112721882f25d4659ede075fc6b520d61
homepage   : https://kde.org/applications/utilities/org.kde.kgpg
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - akonadi-contacts-devel
    - gpgme-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
