name       : kgpg
version    : 19.08.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kgpg-19.08.2.tar.xz : 90795c649cd32b65b6030ed965e0db5b0570719afa36abb5d4893268461aa841
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - pkgconfig(Qt5Gui)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcodecs-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
