name       : kgpg
version    : 20.12.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kgpg-20.12.2.tar.xz : af83c3124f941d5ebc8eab00e8b38250e1a86925b63f918b2629765bab33efeb
homepage   : https://kde.org/applications/utilities/org.kde.kgpg
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - akonadi-contacts-devel
    - gpgme-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
